grafana:
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    retention: 6h

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m

    route:
      group_by: ['namespace', 'alertname']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h
      receiver: 'webhook-receiver'
      routes:
        - receiver: 'webhook-receiver'
          matchers:
            - alertname = "PostifyHQWebReplicasUnavailable"

    receivers:
      - name: 'webhook-receiver'
        webhook_configs:
          - url: 'http://alertmanager-webhook-receiver.monitoring.svc.cluster.local:8080/alert'
            send_resolved: true
