apiVersion: v1
kind: Service
metadata:
  name: postifyhq-mysql
  namespace: postifyhq
  labels:
    app.kubernetes.io/name: postifyhq
    app.kubernetes.io/part-of: workhour-platform
    app.kubernetes.io/component: mysql
    app.kubernetes.io/managed-by: kubectl
    environment: development
    team: platform-engineering
spec:
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
  selector:
    app.kubernetes.io/name: postifyhq
    app.kubernetes.io/component: mysql
