apiVersion: v1
kind: Secret
metadata:
  name: postifyhq-secret
  namespace: postifyhq
  labels:
    app.kubernetes.io/name: postifyhq
    app.kubernetes.io/part-of: workhour-platform
    app.kubernetes.io/component: application-secret
    app.kubernetes.io/managed-by: kubectl
    environment: development
    team: platform-engineering
type: Opaque
stringData:
  DB_USERNAME: "postifyhq"
  DB_PASSWORD: "change-me-local-db-password"
  MYSQL_ROOT_PASSWORD: "change-me-local-root-password"
  JWT_SECRET: "change-me-local-jwt-secret"
  API_KEY: "change-me-local-api-key"
  MAIL_USERNAME: "change-me-local-mail-user"
  MAIL_PASSWORD: "change-me-local-mail-password"
