apiVersion: v1
kind: Service
metadata:
  name: postifyhq-web
  namespace: postifyhq
  labels:
    app.kubernetes.io/name: postifyhq
    app.kubernetes.io/part-of: workhour-platform
    app.kubernetes.io/component: web
    app.kubernetes.io/managed-by: kubectl
    environment: development
    team: platform-engineering
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: postifyhq
    app.kubernetes.io/component: web
